# Generated by Django 4.1.3 on 2023-05-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="textfile",
            name="data_type",
            field=models.CharField(default="Image", max_length=5),
            preserve_default=False,
        ),
    ]
